spring.application.name=circula-book
spring.datasource.url=jdbc:postgresql://localhost:5432/circula_book_db
spring.datasource.username=circula_user
spring.datasource.password=circula_senha_123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.port=8080